version: '3'
tasks:
  build:
    cmds: ["cargo build --workspace --release --locked"]
  run:
    cmds: ["cargo run -p caddy-archive-cli --locked -- {{.CLI_ARGS}}"]
  check:
    cmds:
      - cargo fmt --all -- --check
      - cargo clippy --workspace --all-targets --all-features --locked -- -D warnings
      - cargo test --workspace --all-features --locked
  bench:cab:
    cmds: ["cargo bench --manifest-path ../cabinet/Cargo.toml --bench cab --locked -- {{.CLI_ARGS}}"]
  fuzz:check:
    cmds:
      - cargo fmt --manifest-path fuzz/Cargo.toml -- --check
      - cargo clippy --manifest-path fuzz/Cargo.toml --all-targets --locked -- -D warnings
      - cargo test --manifest-path fuzz/Cargo.toml --locked
