#!/usr/bin/env python3
"""Baseline payload interoperability probes; this is not a full parity audit.

Requires a built arc (--arc) and the pinned 7-Zip 26.04 (--reference).
An explicitly allowed version mismatch still exits 2 and cannot claim pinned
conformance. Temporary fixtures disappear unless --artifacts is supplied.
"""

import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import tempfile
import zipfile

PIN = "26.04"
COMMIT = "9128b80e3a471108678e2b3ec3c985861c8d7b0f"
SOURCE = f"https://github.com/ip7z/7zip/blob/{COMMIT}/CPP/7zip/"
PROFILES = {
    "zip-copy": ("zip", "copy", ["-m0=Copy"], "Archive/Zip/ZipHandlerOut.cpp"),
    "zip-deflate": ("zip", "deflate", ["-m0=Deflate"], "Archive/Zip/ZipHandlerOut.cpp"),
    "7z-copy": ("7z", "copy", ["-m0=Copy", "-ms=off"], "Archive/7z/7zHandlerOut.cpp"),
    "7z-lzma2": ("7z", "lzma2", ["-m0=LZMA2", "-ms=off"], "Archive/7z/7zHandlerOut.cpp"),
    "tar": ("tar", None, [], "Archive/Tar/TarHandler.cpp"),
}


def digest(path):
    h = hashlib.sha256()
    with Path(path).open("rb") as stream:
        for block in iter(lambda: stream.read(1024 * 1024), b""):
            h.update(block)
    return h.hexdigest()


def run(argv, cwd, timeout):
    """No shell, no inherited stdin; keep diagnostics in the evidence report."""
    evidence_argv = ["-p<redacted>" if str(value).startswith("-p") and not str(value).startswith("--") and len(str(value)) > 2
                     else str(value) for value in argv]
    record = {"argv": evidence_argv, "exit_code": None, "timed_out": False}
    # Spool logs rather than hold an arbitrary child output in process memory.
    with tempfile.TemporaryFile() as stdout, tempfile.TemporaryFile() as stderr:
        try:
            result = subprocess.run(argv, cwd=cwd, stdin=subprocess.DEVNULL,
                                    stdout=stdout, stderr=stderr,
                                    timeout=timeout, check=False)
            record["exit_code"] = result.returncode
        except subprocess.TimeoutExpired:
            record["timed_out"] = True
        except OSError as error:
            record["launch_error"] = str(error)
        for name, stream in (("stdout", stdout), ("stderr", stderr)):
            length = stream.tell()
            stream.seek(0)
            h = hashlib.sha256()
            for block in iter(lambda: stream.read(1024 * 1024), b""):
                h.update(block)
            stream.seek(0)
            record[name] = stream.read(65536).decode("utf-8", "replace")
            record[name + "_bytes"] = length
            record[name + "_sha256"] = h.hexdigest()
            record[name + "_truncated"] = length > 65536
    return record


def executable(name):
    found = shutil.which(name)
    if found is None:
        return {"requested": name, "available": False}
    path = Path(found).resolve()
    return {"requested": name, "available": True, "path": str(path), "sha256": digest(path)}


def tree_hashes(root):
    return {p.relative_to(root).as_posix(): digest(p)
            for p in sorted(root.rglob("*")) if p.is_file()}


def probe(profile, reference, arc, root, timeout):
    fmt, method, switches, source = PROFILES[profile]
    work = root / profile
    work.mkdir()
    fixtures = work / "input"
    (fixtures / "nested").mkdir(parents=True)
    (fixtures / "hello.txt").write_bytes(b"archive-rs compatibility fixture\n" * 100)
    (fixtures / "nested" / "binary.bin").write_bytes(bytes(range(256)) * 17)
    (fixtures / "empty").write_bytes(b"")
    for path in fixtures.rglob("*"):
        os.utime(path, (1700000000, 1700000000))
    expected = tree_hashes(fixtures)
    record = {"id": f"baseline.{profile}.payload-roundtrip", "source": SOURCE + source,
              "scope": "create/list/test/extract acceptance and extracted payload hashes; metadata and effective codec tuning are not compared",
              "fixtures": {"provenance": "generated by this script; fixed bytes and Unix mtime 1700000000", "sha256": expected},
              "commands": [], "extractions": []}
    for producer in ("reference", "arc"):
        archive = work / f"{producer}.{fmt}"
        if producer == "reference":
            command = [reference, "a", f"-t{fmt}", *switches, str(archive), "."]
        else:
            command = [arc, "create", "--format", fmt, "--input", str(fixtures), "--output", str(archive)]
            if method:
                command += ["--compression", method]
        record["commands"].append(run(command, fixtures, timeout))
        for consumer, tool in (("reference", reference), ("arc", arc)):
            for operation in ("list", "test"):
                command = ([tool, {"list": "l", "test": "t"}[operation], str(archive)]
                           if consumer == "reference" else [tool, operation, str(archive)])
                record["commands"].append(run(command, work, timeout))
            destination = work / f"{producer}-to-{consumer}"
            command = ([tool, "x", "-y", str(archive), f"-o{destination}"]
                       if consumer == "reference" else [tool, "extract", str(archive), "--output", str(destination)])
            result = run(command, work, timeout)
            record["commands"].append(result)
            actual = tree_hashes(destination)
            record["extractions"].append({"producer": producer, "consumer": consumer,
                                          "sha256": actual, "matches_fixtures": actual == expected})
    record["passed"] = (all(c["exit_code"] == 0 for c in record["commands"])
                        and all(e["matches_fixtures"] for e in record["extractions"]))
    return record


def edit_probe(kind, reference, arc, root, timeout):
    """Compare the narrow native ZIP name-edit profile with reference rn/d."""
    work = root / f"edit-{kind}"
    work.mkdir()
    fixtures = work / "input"
    (fixtures / "nested").mkdir(parents=True)
    (fixtures / "nested2").mkdir()
    (fixtures / "nested" / "payload.txt").write_bytes(b"directory payload\n" * 100)
    (fixtures / "nested2" / "payload.txt").write_bytes(b"boundary sibling\n" * 100)
    (fixtures / "root.txt").write_bytes(b"root payload\n" * 100)
    expected = tree_hashes(fixtures)
    original_hashes = dict(expected)
    if kind == "rename-directory":
        old, new = "nested/", "moved/"
        expected = {new + name[len(old):] if name.startswith(old) else name: value
                    for name, value in expected.items()}
    elif kind == "delete-directory":
        old, new = "nested/", None
        expected = {name: value for name, value in expected.items() if not name.startswith(old)}
    elif kind == "rename-exact":
        old, new = "root.txt", "renamed.txt"
        expected[new] = expected.pop(old)
    else:
        old, new = "root.txt", None
        del expected[old]
    record = {"id": f"native.zip.{kind}", "source": SOURCE + "UI/Common/Update.cpp",
              "scope": "native ZIP name editing versus reference rn/d; payload hashes and archive comment only",
              "fixtures": {"provenance": "generated fixed byte payloads; pinned reference ZIP creation and Python stdlib archive comment attachment",
                           "sha256": original_hashes}, "commands": [], "extractions": [], "comments": []}
    base = work / "source.zip"
    result = run([reference, "a", "-tzip", "-m0=Deflate", str(base), "."], fixtures, timeout)
    record["commands"].append(result)
    if result["exit_code"] != 0 or not base.is_file():
        record["passed"] = False
        return record
    comment = b"archive-rs ZIP name editing comment fixture"
    with zipfile.ZipFile(base, "a") as archive:
        archive.comment = comment
    record["fixtures"]["source_archive_sha256"] = digest(base)
    record["fixtures"]["archive_comment_hex"] = comment.hex()
    for producer in ("reference", "arc"):
        archive_path = work / f"{producer}.zip"
        shutil.copyfile(base, archive_path)
        command = ([reference, "rn", str(archive_path), old, new]
                   if new else [reference, "d", str(archive_path), old]) if producer == "reference" else (
                   [arc, "rename", str(archive_path), "--pair", old, new]
                   if new else [arc, "delete", str(archive_path), "--name", old])
        record["commands"].append(run(command, work, timeout))
        try:
            with zipfile.ZipFile(archive_path) as archive:
                actual_comment = archive.comment
            record["comments"].append({"producer": producer, "hex": actual_comment.hex(),
                                       "preserved": actual_comment == comment})
        except (OSError, zipfile.BadZipFile) as error:
            record["comments"].append({"producer": producer, "preserved": False, "error": str(error)})
        for consumer, tool in (("reference", reference), ("arc", arc)):
            for operation in ("list", "test"):
                command = ([tool, {"list": "l", "test": "t"}[operation], str(archive_path)]
                           if consumer == "reference" else [tool, operation, str(archive_path)])
                record["commands"].append(run(command, work, timeout))
            destination = work / f"{producer}-to-{consumer}"
            command = ([tool, "x", "-y", str(archive_path), f"-o{destination}"]
                       if consumer == "reference" else [tool, "extract", str(archive_path), "--output", str(destination)])
            record["commands"].append(run(command, work, timeout))
            actual = tree_hashes(destination)
            record["extractions"].append({"producer": producer, "consumer": consumer,
                                          "sha256": actual, "matches_expected": actual == expected})
    record["expected_sha256"] = expected
    record["passed"] = (all(c["exit_code"] == 0 for c in record["commands"])
                        and all(e["matches_expected"] for e in record["extractions"])
                        and all(c["preserved"] for c in record["comments"]))
    return record


def check(args, root):
    reference, arc = executable(args.reference), executable(args.arc)
    report = {"schema_version": 1, "reference_pin": {"version": PIN, "source_commit": COMMIT},
              "harness_sha256": digest(__file__),
              "reference": reference, "arc": arc, "probes": [], "pinned_conformance": False,
              "scope": "baseline interoperability only; not full 7-Zip option or update parity"}
    if not reference["available"]:
        report["status"] = "reference-unavailable"
        return report, 2
    info = run([reference["path"], "i"], root, args.timeout)
    reference["build_configuration"] = info
    reference["source_provenance"] = {
        "declared_commit": getattr(args, "reference_source_commit", None),
        "verification": "caller supplied; executable version does not prove source provenance",
    }
    match = re.search(r"^7-Zip(?:\s+(?:\[[^\]]+\]|\([az]\)))?\s+(\d+\.\d+)(?=\s|$)",
                      info["stdout"], re.MULTILINE)
    reference["version"] = match.group(1) if match else None
    pinned = reference["version"] == PIN and info["exit_code"] == 0
    if not pinned and not args.allow_reference_mismatch:
        report["status"] = "reference-pin-mismatch"
        return report, 2
    if not arc["available"]:
        report["status"] = "arc-unavailable"
        return report, 2
    arc["version_output"] = run([arc["path"], "--version"], root, args.timeout)
    report["probes"] = [probe(p, reference["path"], arc["path"], root, args.timeout)
                        for p in args.profile or PROFILES]
    if getattr(args, "edit_probes", False):
        report["probes"].extend(edit_probe(kind, reference["path"], arc["path"], root, args.timeout)
                                for kind in ("rename-directory", "delete-directory", "rename-exact", "delete-exact"))
    passed = all(p["passed"] for p in report["probes"])
    report["pinned_conformance"] = pinned and passed
    report["status"] = "passed" if pinned and passed else "failed" if pinned else "unpinned-evidence"
    return report, (0 if pinned and passed else 1 if pinned else 2)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--reference", default="7zz")
    parser.add_argument("--arc", default="target/debug/arc")
    parser.add_argument("--allow-reference-mismatch", action="store_true")
    parser.add_argument("--reference-source-commit", help="caller-declared build source commit; recorded without claiming source verification")
    parser.add_argument("--profile", action="append", choices=PROFILES)
    parser.add_argument("--edit-probes", action="store_true", help="also compare the narrow native ZIP rename/delete profile with reference rn/d")
    parser.add_argument("--timeout", type=float, default=60)
    parser.add_argument("--report", type=Path, help="JSON output (default: stdout)")
    parser.add_argument("--artifacts", type=Path, help="retain artifacts in a new directory")
    args = parser.parse_args()
    if not 0 < args.timeout <= 3600:
        parser.error("--timeout must be greater than zero and at most 3600 seconds")
    if args.artifacts:
        args.artifacts.mkdir(parents=True, exist_ok=False)
        report, code = check(args, args.artifacts.resolve())
        report["artifacts"] = str(args.artifacts.resolve())
    else:
        with tempfile.TemporaryDirectory(prefix="archive-compatibility-") as directory:
            report, code = check(args, Path(directory))
    output = json.dumps(report, indent=2) + "\n"
    if args.report:
        args.report.write_text(output, encoding="utf-8")
    else:
        print(output, end="")
    return code


if __name__ == "__main__":
    raise SystemExit(main())
