[package]
name = "caddy-archive-fs"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
description = "Filesystem extraction for caddy-archive"

[lib]
name = "archive_fs"

[dependencies]
archive-core = { version = "0.3.0", package = "caddy-archive-core", path = "../archive-core" }
libc.workspace = true
tempfile.workspace = true

[lints]
workspace = true
